version: "2"
services:
  db:
    image: postgres
    env_file:
      - .env.docker
    environment:
      POSTGRES_USER: $${DB_USER}
      POSTGRES_PASSWORD: $${DB_PASS}
    ports:
      - 5431:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
